### ISSUE TITLE
pretrained model ?

### ISSUE THREAD

**Issue by samiulextreem** [quenting44/drl-grasping#4]
It would be very helpful if pretrained model is available in  GitHub.

**Comment by qgallouedec** [comment]
Hello @samiulextreem,

Actually, they are pertained model, please take a look at [rl-trained-agents](https://github.com/DLR-RM/rl-trained-agents/).

**Comment by qgallouedec** [comment]
You will also need to take a look at [rl-baselines3-zoo](https://github.com/DLR-RM/rl-baselines3-zoo) to load the policies. 

Hoping to have helped you.
